language: android

sudo: false

before_install:
    - openssl aes-256-cbc -K $encrypted_e2d0f76750b6_key -iv $encrypted_e2d0f76750b6_iv -in maven.keystore.gpg.enc -out maven.keystore.gpg -d
    - chmod +x gradlew

jdk:
    - oraclejdk8

android:
  components:
    - tools
    - android-23
    - build-tools-23.0.2
    - extra-android-m2repository

script:
    - echo "Travis branch is $TRAVIS_BRANCH"
    - echo "Travis branch is in pull request? $TRAVIS_PULL_REQUEST"
    - echo "Travis tag $TRAVIS_TAG"
    - echo -e "signing.keyId=${signing_keyId}" >> "gradle.properties"
    - echo -e "signing.password=${signing_password}" >> "gradle.properties"
    - echo -e "signing.secretKeyRingFile=../maven.keystore.gpg" >> "gradle.properties"
    - gradle clean check uploadArchives --continue

install:
    - true

notifications:
    email:
        - toxicbakery@gmail.com